version: '3.8'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/PublicDiscussion/static
      - media_volume:/usr/src/PublicDiscussion/media
    expose:
      - 8000
    env_file: .env.dev

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env.dev

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/PublicDiscussion/static
      - media_volume:/usr/src/PublicDiscussion/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: